"""
=============================================================================
MODULE 13 - EXERCISE 08: Reasoning Chain Analysis
=============================================================================

YOUR TASK:
  Implement functions that analyze reasoning chain responses —
  the kind generated by RLVR-trained models like DeepSeek-R1.

RULES:
  - Only Python stdlib (re module already imported)
  - Read each docstring carefully
  - Tests at the bottom verify your work

RUN WITH:  python exercise_08_reasoning.py
=============================================================================
"""

import re


# =============================================================================
# EXERCISE 1: Extract Think Block
# =============================================================================

def extract_think_block(response: str) -> str:
    """
    Extract the content inside <think>...</think> tags.

    If no think block is present, return empty string "".

    Parameters:
      response : full model response

    Returns:
      content inside <think>...</think>, stripped of leading/trailing whitespace
      or "" if no think block exists

    EXAMPLES:
      "<think>step 1: x=5</think> 5"  ->  "step 1: x=5"
      "42"                             ->  ""
      "<think></think> 42"             ->  ""

    HINTS:
      - re.search(r'<think>(.*?)</think>', response, re.DOTALL)
      - re.DOTALL makes '.' match newlines
      - match.group(1) gets the captured group (content inside tags)
      - .strip() removes leading/trailing whitespace
    """
    # YOUR CODE HERE
    pass


# =============================================================================
# EXERCISE 2: Count Reasoning Steps
# =============================================================================

def count_reasoning_steps(think_content: str) -> int:
    """
    Count the number of explicit reasoning steps in a think block.

    A "step" is a line that starts with:
      - "Step N:" or "Step N."
      - A number followed by ")" or "." e.g. "1." or "2)"
      - A bullet point "-" at the start of a line

    Return 0 if think_content is empty.
    Return at least 1 if think_content is non-empty (even with no explicit steps).

    Parameters:
      think_content : the text inside <think>...</think>

    Returns:
      int — number of steps detected

    EXAMPLES:
      "Step 1: ...\nStep 2: ..."   ->  2
      "1. first\n2. second"        ->  2
      "- bullet one\n- bullet two" ->  2
      "just some text"             ->  1
      ""                           ->  0

    HINTS:
      - Split by newline: think_content.split('\\n')
      - Check each line with re.match(r'^\\s*(Step\\s+\\d|\\d+[.)\\s]|\\-\\s)', line)
      - If count == 0 but think_content is non-empty, return 1
    """
    # YOUR CODE HERE
    pass


# =============================================================================
# EXERCISE 3: Detect Backtracking
# =============================================================================

def has_backtracking(think_content: str) -> bool:
    """
    Detect if the model reconsidered or backtracked during reasoning.

    Return True if the think block contains any of these phrases
    (case-insensitive):
      "wait", "actually", "let me reconsider", "that's wrong",
      "i made an error", "let me redo", "no,", "hmm,",
      "let me try again", "that doesn't seem right"

    Parameters:
      think_content : the text inside <think>...</think>

    Returns:
      True if any backtracking phrase found, False otherwise

    HINTS:
      - think_content.lower() converts to lowercase for case-insensitive matching
      - Use 'phrase in text' to check substring presence
    """
    # YOUR CODE HERE
    backtrack_phrases = [
        "wait", "actually", "let me reconsider", "that's wrong",
        "i made an error", "let me redo", "no,", "hmm,",
        "let me try again", "that doesn't seem right"
    ]
    # YOUR CODE HERE
    pass


# =============================================================================
# EXERCISE 4: Detect Self-Verification
# =============================================================================

def has_verification(think_content: str) -> bool:
    """
    Detect if the model verified its answer during reasoning.

    Return True if the think block contains any of these phrases
    (case-insensitive):
      "let me verify", "let me check", "verify:", "checking:",
      "to confirm", "double-check", "let me double", "indeed"

    Parameters:
      think_content : the text inside <think>...</think>

    Returns:
      True if any verification phrase found, False otherwise
    """
    verify_phrases = [
        "let me verify", "let me check", "verify:", "checking:",
        "to confirm", "double-check", "let me double", "indeed"
    ]
    # YOUR CODE HERE
    pass


# =============================================================================
# EXERCISE 5: Compute Reasoning Quality Score
# =============================================================================

def reasoning_quality_score(response: str) -> float:
    """
    Compute a quality score for the reasoning in a response.

    Score components (max 1.0 total):
      - Uses <think> tags:    +0.30
      - Steps (scaled):       +0.30 * min(num_steps / 5.0, 1.0)
      - Has backtracking:     +0.20
      - Has verification:     +0.20

    Parameters:
      response : full model response string

    Returns:
      float in [0.0, 1.0]

    EXAMPLE:
      response = "<think>Step 1: ...\nStep 2: ...\nLet me verify.\n</think> 42"
      think = "Step 1: ...\nStep 2: ...\nLet me verify."
      has_think = True       -> +0.30
      steps = 2              -> +0.30 * (2/5) = +0.12
      backtracking = False   -> +0.00
      verification = True    -> +0.20
      total = 0.30 + 0.12 + 0.00 + 0.20 = 0.62

    HINTS:
      - Use your extract_think_block(), count_reasoning_steps(),
        has_backtracking(), has_verification() functions
    """
    # YOUR CODE HERE
    pass


# =============================================================================
# TESTS — DO NOT MODIFY BELOW THIS LINE
# =============================================================================

def run_tests():
    print("=" * 55)
    print("EXERCISE 08 TESTS")
    print("=" * 55)
    passed = 0
    total = 0

    def check(name, got, expected, tol=0.01):
        nonlocal passed, total
        total += 1
        if isinstance(expected, bool):
            ok = (got == expected)
        elif isinstance(expected, int):
            ok = (got == expected)
        elif isinstance(expected, str):
            ok = (got == expected)
        else:
            ok = abs(float(got) - float(expected)) < tol
        status = "PASS" if ok else "FAIL"
        if ok:
            passed += 1
        print(f"  [{status}] {name}")
        if not ok:
            print(f"         Expected: {expected!r}")
            print(f"         Got:      {got!r}")

    # --- extract_think_block ---
    check("extract_think: basic",
          extract_think_block("<think>hello</think> 42"), "hello")
    check("extract_think: multiline",
          extract_think_block("<think>\nstep 1\nstep 2\n</think> 5"),
          "step 1\nstep 2")
    check("extract_think: no tags",
          extract_think_block("42"), "")
    check("extract_think: empty block",
          extract_think_block("<think></think> 42"), "")

    # --- count_reasoning_steps ---
    check("steps: numbered list",
          count_reasoning_steps("1. first\n2. second\n3. third"), 3)
    check("steps: Step keyword",
          count_reasoning_steps("Step 1: do this\nStep 2: do that"), 2)
    check("steps: bullets",
          count_reasoning_steps("- item one\n- item two"), 2)
    check("steps: no explicit steps (non-empty)",
          count_reasoning_steps("just some reasoning here"), 1)
    check("steps: empty string",
          count_reasoning_steps(""), 0)

    # --- has_backtracking ---
    check("backtrack: 'wait' present",
          has_backtracking("Let me compute... wait, that's wrong"), True)
    check("backtrack: 'actually' present",
          has_backtracking("I said 5, actually it is 6"), True)
    check("backtrack: none present",
          has_backtracking("Step 1: x=5. Step 2: answer is 5."), False)
    check("backtrack: case insensitive",
          has_backtracking("WAIT, I need to recheck"), True)

    # --- has_verification ---
    check("verify: 'let me verify' present",
          has_verification("Let me verify: 12 * 12 = 144. Yes."), True)
    check("verify: 'double-check' present",
          has_verification("Let me double-check my answer."), True)
    check("verify: none present",
          has_verification("Step 1: compute 5 + 3 = 8."), False)
    check("verify: 'indeed' present",
          has_verification("Indeed, the answer is correct."), True)

    # --- reasoning_quality_score ---
    response_full = (
        "<think>\n"
        "Step 1: identify the values.\n"
        "Step 2: compute.\n"
        "Step 3: double-check result.\n"
        "</think> 42"
    )
    score_full = reasoning_quality_score(response_full)
    check("quality: full response > 0.5", score_full > 0.5, True)
    check("quality: full response <= 1.0", score_full <= 1.0, True)

    score_empty = reasoning_quality_score("42")
    check("quality: no thinking = 0.0", score_empty, 0.0)

    response_think_only = "<think>some reasoning</think> 42"
    score_think = reasoning_quality_score(response_think_only)
    check("quality: think only >= 0.3", score_think >= 0.3, True)
    check("quality: think only <= 0.5", score_think <= 0.5, True)

    print(f"\n{passed}/{total} tests passed")
    if passed == total:
        print("All tests passed!")
    else:
        print("Some tests failed. Re-read the docstrings and try again.")


if __name__ == "__main__":
    run_tests()
