"""
=============================================================================
EXAMPLE 03 (PyTorch Version): Bigram Language Model as nn.Module
=============================================================================

GLOSSARY
---------
nn.Module        : Base class for ALL neural network layers/models in PyTorch.
                   Every model you build inherits from this.
                   C# analogy: like an abstract base class — you MUST call
                   super().__init__() and implement forward().

forward()        : The method that runs the model on input data.
                   You define it. PyTorch calls it when you do model(x).
                   C# analogy: like overriding operator() or Invoke().

loss.backward()  : Computes gradients for EVERY parameter in the model.
                   One line replaces pages of manual calculus.

optimizer.step() : Updates all parameters using their gradients.
                   One line replaces all the W -= lr * grad lines.

optimizer.zero_grad() : Resets all gradients to zero before the next step.
                        Must be called each training iteration.
                        C# analogy: clearing a sum accumulator before reuse.

F.cross_entropy  : PyTorch's built-in loss function for classification.
                   Input  : logits shape (N, C) and targets shape (N,)
                   Output : scalar loss value
                   Internally applies softmax + negative log likelihood.

=============================================================================
HOW THIS CONNECTS TO THE NumPy VERSION (example_03_nanogpt.py)
=============================================================================

NumPy version (Part A):
  - Manually counted pairs, built a probability table
  - No learning — just counting
  - Generated by doing np.random.choice(row_probs)

PyTorch version (Part A — this file):
  - Same bigram idea, but as an nn.Module
  - nn.Embedding(vocab_size, vocab_size) IS the probability table
  - We TRAIN it using cross-entropy loss + backpropagation
  - Same generation logic but with torch.multinomial

Why is this better?
  - The model LEARNS the probabilities from data (not just counts)
  - Gradient descent finds the best weights automatically
  - Same structure scales up: just add more layers → GPT!

=============================================================================
"""

import torch                        # core PyTorch
import torch.nn as nn               # building blocks
import torch.nn.functional as F     # standalone functions

print("=" * 60)
print("PART A: Bigram Model as nn.Module (PyTorch)")
print("=" * 60)

# =============================================================================
# STEP 1: Same text preparation as NumPy version
# =============================================================================

text = "hello"   # tiny training text — same as NumPy version

# Build vocabulary: find all unique characters, sort them for consistency
chars = sorted(set(text))           # ['e', 'h', 'l', 'o']
vocab_size = len(chars)

# Mapping from char → integer and integer → char
char_to_idx = {ch: i for i, ch in enumerate(chars)}
idx_to_char = {i: ch for i, ch in enumerate(chars)}

print(f"Training text  : '{text}'")
print(f"Unique chars   : {chars}")
print(f"Vocabulary size: {vocab_size}")
print(f"Char → ID map  : {char_to_idx}")

# Encode the text as a tensor of integer token IDs
# dtype=torch.long because token IDs must be integers
data = torch.tensor([char_to_idx[ch] for ch in text], dtype=torch.long)
print(f"Encoded text   : {data.tolist()}  (same values as NumPy version)")

# =============================================================================
# STEP 2: Create training pairs (input, target) as tensors
# =============================================================================

print("\n--- STEP 2: Training Pairs ---")
print("""
Same logic as NumPy version:
  Input (x): current character
  Target (y): next character

From "hello":
  h(2) -> e(0)
  e(0) -> l(1)
  l(1) -> l(1)
  l(1) -> o(3)

Now they are PyTorch tensors, not Python lists.
""")

# data[:-1] = all characters except the last
# data[1:]  = all characters except the first
# So x[i] and y[i] are a (current, next) pair
x_train = data[:-1]   # inputs:  h, e, l, l  (first 4 chars)
y_train = data[1:]    # targets: e, l, l, o  (last 4 chars)

print("Training pairs:")
for i in range(len(x_train)):
    src = idx_to_char[x_train[i].item()]   # .item() extracts Python int from tensor
    tgt = idx_to_char[y_train[i].item()]
    print(f"  '{src}' ({x_train[i].item()}) -> '{tgt}' ({y_train[i].item()})")

# =============================================================================
# STEP 3: Define the Bigram Model as an nn.Module
# =============================================================================

print("\n--- STEP 3: Bigram Model ---")
print("""
A bigram model needs ONE table: for each token, what is the score for
each possible next token?

  Shape of table: (vocab_size, vocab_size)
  Row i = "if current token is i, these are the scores for next token"

In PyTorch, this IS an nn.Embedding layer:
  nn.Embedding(vocab_size, vocab_size)
  - Row i = the logits for the next token given current token is i

Why nn.Embedding and not nn.Linear?
  - nn.Embedding does a simple ROW LOOKUP by integer index.
  - nn.Linear multiplies a float vector by a weight matrix.
  - Since our input is a single integer (token ID), Embedding is the right tool.
  - Under the hood: Embedding.weight is a (vocab_size, vocab_size) matrix.
    Looking up token i just returns row i. That's it!

C# analogy:
  float[,] table = new float[vocabSize, vocabSize];
  float[] nextScores = table[currentTokenId];  // get one row
""")

class BigramModel(nn.Module):
    """
    Simplest possible language model.
    One nn.Embedding layer IS the entire model.
    """

    def __init__(self, vocab_size):
        super().__init__()   # MUST call parent __init__

        # The lookup table:
        #   Input:  token ID (integer 0..vocab_size-1)
        #   Output: vocab_size logits (one score per possible next token)
        # This single table IS the whole bigram model.
        self.table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        """
        idx     : input token IDs,  shape (batch_size,) or (batch_size, seq_len)
        targets : target token IDs, same shape as idx — optional
        returns : (logits, loss)
                  logits shape: (batch_size, vocab_size) or (N, vocab_size)
                  loss  : scalar tensor if targets given, else None
        """
        # Look up logits for each input token
        # self.table(idx) = lookup row idx in the embedding table
        logits = self.table(idx)    # shape: (batch_size, vocab_size)

        loss = None
        if targets is not None:
            # F.cross_entropy expects:
            #   logits  shape: (N, C) — N examples, C classes
            #   targets shape: (N,)   — correct class index for each example
            # Our logits shape: (batch_size, vocab_size)
            # Our targets shape: (batch_size,)
            # They already match — no reshaping needed here.
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    @torch.no_grad()   # no gradient tracking during generation
    def generate(self, start_idx, num_chars, idx_to_char):
        """
        Generate text autoregressively.
        start_idx : starting token ID (integer)
        num_chars : number of characters to generate
        """
        # Start with a (1, 1) tensor — batch of 1, sequence of 1 token
        current = torch.tensor([[start_idx]], dtype=torch.long)
        result_chars = [idx_to_char[start_idx]]

        for _ in range(num_chars - 1):
            # Forward pass: get logits for current token
            logits, _ = self(current[:, -1])    # pass only the last token

            # Convert logits to probabilities using softmax
            # dim=-1 means softmax over the last dimension (vocab dimension)
            probs = F.softmax(logits, dim=-1)    # shape: (1, vocab_size)

            # Sample the next token from the probability distribution
            # torch.multinomial: like np.random.choice(p=probs)
            # num_samples=1 means pick 1 token
            next_idx = torch.multinomial(probs, num_samples=1)    # shape: (1, 1)

            # Append new token to sequence
            # torch.cat joins tensors along a dimension
            current = torch.cat([current, next_idx], dim=1)       # (1, seq_len+1)

            # Record the character
            result_chars.append(idx_to_char[next_idx.item()])

        return ''.join(result_chars)


# =============================================================================
# STEP 4: Instantiate model and inspect it
# =============================================================================

model = BigramModel(vocab_size)

# Count trainable parameters
n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Model created!")
print(f"  Vocab size       : {vocab_size}")
print(f"  Table shape      : {model.table.weight.shape}")
print(f"  Trainable params : {n_params}  (vocab_size x vocab_size = {vocab_size}x{vocab_size})")

# =============================================================================
# STEP 5: Training loop
# =============================================================================

print("\n--- STEP 5: Training the Bigram Model ---")
print("""
PyTorch training loop — 3 lines replace manual gradient code:

  optimizer.zero_grad()   <- clear old gradients
  loss.backward()         <- compute new gradients (automatic!)
  optimizer.step()        <- update weights

Compare to NumPy where we manually computed:
  gradient = 2 * (prediction - target) * x
  W = W - lr * gradient
""")

# SGD = Stochastic Gradient Descent (simplest optimizer)
# lr = learning rate: how big a step to take each update
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

print(f"Training for 200 steps on text '{text}':")
print()

for step in range(200):
    # --- Forward pass ---
    logits, loss = model(x_train, y_train)   # compute predictions + loss

    # --- Backward pass (3 lines!) ---
    optimizer.zero_grad()    # clear gradients from last step (important!)
    loss.backward()          # PyTorch computes ALL gradients automatically
    optimizer.step()         # update all weights by one gradient-descent step

    # Print progress every 50 steps
    if step % 50 == 0:
        print(f"  Step {step:3d}: loss = {loss.item():.4f}")

print(f"\nFinal loss: {loss.item():.4f}")
print("Lower loss = model learned the patterns better.")
print("(Math: loss = -log(probability of correct next token))")

# =============================================================================
# STEP 6: Generate text
# =============================================================================

print("\n--- STEP 6: Generate Text ---")
print("""
Generation is autoregressive:
  1. Give the model a starting character
  2. Model outputs scores for the next character
  3. Pick next character (randomly, weighted by scores)
  4. Feed that back as input
  5. Repeat

This is EXACTLY how GPT-4 generates text — just much larger!
""")

print("Generating text starting with 'h'  (5 trials):")
start_id = char_to_idx['h']
for trial in range(5):
    generated = model.generate(start_id, num_chars=8, idx_to_char=idx_to_char)
    print(f"  Trial {trial + 1}: '{generated}'")

print("\nNote: model learned h->e, e->l, etc. from just 4 training pairs!")
print("(Variety comes from sampling — not always the top choice.)")

# =============================================================================
# PART B: Context-Aware Bigram with Nursery Rhyme
# =============================================================================

print("\n" + "=" * 60)
print("PART B: Bigger Bigram on Nursery Rhyme (Character-Level GPT)")
print("=" * 60)

print("""
NumPy version (Part B) used a dictionary of probability tables.
PyTorch version: same nn.Module but on more data.

This shows that the EXACT same model architecture scales to larger text.
Training loop is identical — only vocab_size and data length change.
""")

# Same nursery rhyme as NumPy version
training_text = (
    "mary had a little lamb little lamb little lamb "
    "mary had a little lamb its fleece was white as snow "
    "and everywhere that mary went mary went mary went "
    "and everywhere that mary went the lamb was sure to go"
)

# Build vocabulary from the nursery rhyme
chars_b    = sorted(set(training_text))
vocab_b    = len(chars_b)
c2i        = {ch: i for i, ch in enumerate(chars_b)}
i2c        = {i: ch for i, ch in enumerate(chars_b)}

# Encode entire text as a single tensor
data_b = torch.tensor([c2i[ch] for ch in training_text], dtype=torch.long)

print(f"Training text  : {len(training_text)} characters")
print(f"Vocabulary size: {vocab_b} unique chars")
print(f"Encoded length : {len(data_b)} token IDs")

# Same x/y split as before
x_b = data_b[:-1]
y_b = data_b[1:]

# Create model for this larger vocabulary
model_b = BigramModel(vocab_b)
n_params_b = sum(p.numel() for p in model_b.parameters() if p.requires_grad)
print(f"Trainable params: {n_params_b}  ({vocab_b}x{vocab_b} table)")

# Train with AdamW (better optimizer for language models)
# AdamW adapts the learning rate for each parameter — faster convergence
optimizer_b = torch.optim.AdamW(model_b.parameters(), lr=1e-2)

print("\nTraining for 500 steps...")
for step in range(500):
    logits_b, loss_b = model_b(x_b, y_b)
    optimizer_b.zero_grad()
    loss_b.backward()
    optimizer_b.step()
    if step % 100 == 0:
        print(f"  Step {step:3d}: loss = {loss_b.item():.4f}")

# Generate text
print("\nGenerating text (seed = 'mary'):")
for trial in range(3):
    seed_id = c2i['m']   # start with 'm'
    generated_b = model_b.generate(seed_id, num_chars=50, idx_to_char=i2c)
    print(f"\n  Trial {trial + 1}: '{generated_b}'")

# =============================================================================
# SUMMARY
# =============================================================================

print("\n" + "=" * 60)
print("SUMMARY: NumPy Bigram vs PyTorch Bigram")
print("=" * 60)
print("""
  NumPy (example_03):                   PyTorch (this file):
  ----------------------------------    ----------------------------------
  counts = np.zeros((V, V))             nn.Embedding(V, V)
  counts[x][y] += 1                     optimizer learns weights
  probs = counts / counts.sum()         F.cross_entropy(logits, targets)
  np.random.choice(probs)               torch.multinomial(softmax(logits))
  Manual counting only                  Gradient descent — LEARNS patterns
  Can't scale to more layers            Add layers → becomes GPT!

Key training loop pattern (memorize this — it repeats in every model!):

  for step in range(num_steps):
      logits, loss = model(x, y)    # forward pass
      optimizer.zero_grad()         # clear old gradients
      loss.backward()               # compute new gradients
      optimizer.step()              # update weights

New PyTorch tools learned:
  nn.Module           base class for all models
  super().__init__()  required — connects your class to PyTorch internals
  forward()           defines the model computation
  F.cross_entropy()   classification loss (softmax + NLL in one call)
  optimizer.zero_grad() / .backward() / .step()  the training trio
  torch.multinomial() weighted random sampling
""")

print("=" * 60)
print("Run example_05_generation_pytorch.py next!")
print("(Example 04 is already PyTorch — shows the full GPT architecture.)")
print("=" * 60)
