"""
Example 08: Training Models on Code (Codex-style)

This example demonstrates:
1. Data preparation for code training
2. Fill-in-the-Middle (FIM) transformation
3. Data augmentation techniques
4. Creating training samples
5. Simple code generation model training

For .NET developers:
- FIM is like IntelliSense that knows context before AND after cursor
- Data preparation is like ETL pipelines in C#
- Training samples are like building a training dataset for ML.NET

Author: Learn LLM from Scratch
Module: 07 - Reasoning and Coding Models
Lesson: 8 - Training on Code
"""

import numpy as np
import random
from typing import List, Tuple, Dict, Optional
from collections import Counter
import re


# ============================================================================
# PART 1: Data Preparation and Cleaning
# ============================================================================

class CodeDataPreprocessor:
    """
    Preprocesses code for training.

    In C#:
    class CodeDataPreprocessor {
        List<string> CleanCode(List<string> rawCode);
    }
    """

    def __init__(self):
        self.stats = {
            'total': 0,
            'filtered': 0,
            'cleaned': 0
        }

    def is_good_quality(self, code: str) -> bool:
        """
        Check if code is suitable for training.

        Filters out:
        - Too short/long code
        - Auto-generated code
        - Minified code
        - Code with too many blank lines

        In C#:
        public bool IsGoodQuality(string code) {
            return CheckLength(code) &&
                   !IsAutoGenerated(code) &&
                   !IsMinified(code);
        }
        """
        # Too short (not useful)
        if len(code.strip()) < 50:
            return False

        # Too long (probably generated or concatenated files)
        if len(code) > 10000:
            return False

        lines = code.split('\n')

        # Check blank line ratio
        non_blank_lines = [l for l in lines if l.strip()]
        if len(lines) == 0:
            return False

        blank_ratio = 1 - (len(non_blank_lines) / len(lines))
        if blank_ratio > 0.6:  # More than 60% blank
            return False

        # Check for auto-generated markers
        code_lower = code.lower()
        auto_markers = [
            'auto-generated',
            'do not edit',
            'generated by',
            'autogenerated',
            '// <auto-generated>',
        ]

        if any(marker in code_lower for marker in auto_markers):
            return False

        # Check for minified code (very long lines)
        max_line_len = max((len(l) for l in lines), default=0)
        if max_line_len > 500:
            return False

        # Must have some code structure (functions/classes)
        has_structure = any(
            keyword in code for keyword in
            ['def ', 'class ', 'function ', 'public ', 'private ']
        )

        if not has_structure:
            return False

        return True

    def clean_code(self, code: str) -> str:
        """
        Clean code for training.

        - Remove excessive blank lines
        - Normalize indentation
        - Remove trailing whitespace

        In C#:
        public string CleanCode(string code) {
            return code
                .RemoveExcessiveBlankLines()
                .NormalizeIndentation()
                .TrimLines();
        }
        """
        lines = code.split('\n')

        # Remove trailing whitespace from each line
        # In C#: lines.Select(l => l.TrimEnd())
        lines = [l.rstrip() for l in lines]

        # Remove excessive consecutive blank lines (max 2)
        cleaned_lines = []
        blank_count = 0

        for line in lines:
            if not line.strip():
                blank_count += 1
                if blank_count <= 2:  # Keep max 2 blank lines
                    cleaned_lines.append(line)
            else:
                blank_count = 0
                cleaned_lines.append(line)

        # Join back
        cleaned = '\n'.join(cleaned_lines)

        return cleaned

    def process_dataset(self, code_samples: List[str]) -> List[str]:
        """
        Process entire dataset.

        Args:
            code_samples: List of raw code snippets

        Returns:
            List of cleaned, filtered code snippets

        In C#:
        public List<string> ProcessDataset(List<string> samples) {
            return samples
                .Where(IsGoodQuality)
                .Select(CleanCode)
                .ToList();
        }
        """
        self.stats['total'] = len(code_samples)

        # Filter and clean
        processed = []

        for code in code_samples:
            if self.is_good_quality(code):
                cleaned = self.clean_code(code)
                processed.append(cleaned)
            else:
                self.stats['filtered'] += 1

        self.stats['cleaned'] = len(processed)

        return processed

    def get_stats(self) -> Dict:
        """Get preprocessing statistics."""
        return self.stats.copy()


# ============================================================================
# PART 2: Fill-in-the-Middle (FIM) Transformation
# ============================================================================

class FIMTransformer:
    """
    Transforms code into Fill-in-the-Middle format.

    FIM format: <fim_prefix>PREFIX<fim_suffix>SUFFIX<fim_middle>MIDDLE

    In C#:
    class FIMTransformer {
        (string prefix, string middle, string suffix) Transform(string code);
    }
    """

    def __init__(self, fim_ratio: float = 0.3):
        """
        Initialize FIM transformer.

        Args:
            fim_ratio: Percentage of samples to apply FIM (default 30%)
        """
        self.fim_ratio = fim_ratio
        self.prefix_token = "<fim_prefix>"
        self.suffix_token = "<fim_suffix>"
        self.middle_token = "<fim_middle>"

    def create_fim_sample(self, code: str) -> Optional[Tuple[str, str, str]]:
        """
        Split code into (prefix, middle, suffix) for FIM training.

        Example:
            Input: "def add(x, y):\\n    return x + y"

            Output:
            - prefix: "def add(x, y):"
            - middle: "\\n    return "
            - suffix: "x + y"

        In C#:
        public (string, string, string)? CreateFIMSample(string code) {
            var splits = FindSplitPoints(code);
            if (splits == null) return null;
            return (prefix, middle, suffix);
        }
        """
        lines = code.split('\n')

        # Need at least 3 lines for meaningful FIM
        if len(lines) < 3:
            return None

        # Choose two split points
        # split1: where prefix ends
        # split2: where middle ends (suffix begins)

        split1 = random.randint(1, len(lines) - 2)
        split2 = random.randint(split1 + 1, len(lines))

        # Create prefix, middle, suffix
        prefix = '\n'.join(lines[:split1])
        middle = '\n'.join(lines[split1:split2])
        suffix = '\n'.join(lines[split2:])

        return prefix, middle, suffix

    def format_fim_training_sample(self, prefix: str, middle: str, suffix: str) -> str:
        """
        Format FIM sample for training.

        Format: <fim_prefix>PREFIX<fim_suffix>SUFFIX<fim_middle>MIDDLE

        The model will learn to predict MIDDLE given PREFIX and SUFFIX.

        In C#:
        public string FormatFIMTrainingSample(
            string prefix, string middle, string suffix) {
            return $"{PrefixToken}{prefix}{SuffixToken}{suffix}{MiddleToken}{middle}";
        }
        """
        formatted = (
            f"{self.prefix_token}{prefix}"
            f"{self.suffix_token}{suffix}"
            f"{self.middle_token}{middle}"
        )

        return formatted

    def transform_batch(self, code_samples: List[str]) -> List[Dict]:
        """
        Transform batch of code into training samples.

        Args:
            code_samples: List of code snippets

        Returns:
            List of training samples (mix of CLM and FIM)

        In C#:
        public List<TrainingSample> TransformBatch(List<string> codeSamples) {
            return codeSamples.Select(code =>
                ShouldApplyFIM(code) ? CreateFIMSample(code) : CreateCLMSample(code)
            ).ToList();
        }
        """
        training_samples = []

        for code in code_samples:
            # Randomly decide if this sample gets FIM treatment
            use_fim = random.random() < self.fim_ratio

            if use_fim:
                # Create FIM sample
                fim_parts = self.create_fim_sample(code)

                if fim_parts is not None:
                    prefix, middle, suffix = fim_parts
                    formatted = self.format_fim_training_sample(
                        prefix, middle, suffix
                    )

                    training_samples.append({
                        'type': 'FIM',
                        'input': formatted,
                        'target': middle,
                        'original': code
                    })
            else:
                # Standard causal language modeling (CLM)
                training_samples.append({
                    'type': 'CLM',
                    'input': code,
                    'target': code,  # Predict next token from previous
                    'original': code
                })

        return training_samples


# ============================================================================
# PART 3: Code Data Augmentation
# ============================================================================

class CodeAugmenter:
    """
    Augment code data to create more diverse training samples.

    In C#:
    class CodeAugmenter {
        List<string> Augment(string code);
    }
    """

    def __init__(self):
        # Common variable name alternatives
        self.var_name_alternatives = {
            'x': ['a', 'val1', 'num1'],
            'y': ['b', 'val2', 'num2'],
            'i': ['idx', 'index', 'counter'],
            'result': ['output', 'res', 'answer'],
            'data': ['values', 'items', 'elements'],
        }

    def rename_variables(self, code: str) -> List[str]:
        """
        Create variations by renaming variables.

        Example:
            def add(x, y): return x + y
            →
            def add(a, b): return a + b
            def add(val1, val2): return val1 + val2

        In C#:
        public List<string> RenameVariables(string code) {
            return variableAlternatives.Select(alt =>
                code.Replace(originalVar, alt)
            ).ToList();
        }
        """
        variations = [code]  # Include original

        # Simple variable renaming (in real world, use AST)
        # For Python functions with simple parameters

        # Find function parameters: def func(x, y):
        param_pattern = r'def\s+\w+\(([\w,\s]+)\):'
        match = re.search(param_pattern, code)

        if match:
            params = [p.strip() for p in match.group(1).split(',')]

            # Try renaming each parameter
            for param in params:
                if param in self.var_name_alternatives:
                    for alt in self.var_name_alternatives[param]:
                        # Replace all occurrences of the parameter
                        # Simple word boundary replacement
                        pattern = r'\b' + param + r'\b'
                        new_code = re.sub(pattern, alt, code)

                        if new_code != code:
                            variations.append(new_code)

        return variations

    def format_variations(self, code: str) -> List[str]:
        """
        Create formatting variations.

        Example:
            def add(x, y): return x + y
            →
            def add(x, y):
                return x + y

        In C#:
        public List<string> FormatVariations(string code) {
            return new List<string> {
                CompactFormat(code),
                ExpandedFormat(code),
                CommentedFormat(code)
            };
        }
        """
        variations = [code]

        # Try compact form (for simple functions)
        if '\n    return' in code:
            # Convert multi-line to single line
            compact = code.replace('\n    return', ': return')
            variations.append(compact)

        # Try expanded form (for single-line functions)
        if ': return' in code:
            # Convert single line to multi-line
            expanded = code.replace(': return', ':\n    return')
            variations.append(expanded)

        return variations

    def add_docstrings(self, code: str) -> List[str]:
        """
        Add docstring variations.

        In C#:
        public List<string> AddDocstrings(string code) {
            return new List<string> {
                code,  // No docstring
                AddShortDocstring(code),
                AddDetailedDocstring(code)
            };
        }
        """
        variations = [code]

        # Extract function name and parameters
        func_pattern = r'def\s+(\w+)\(([\w,\s]*)\):'
        match = re.search(func_pattern, code)

        if match:
            func_name = match.group(1)
            params = match.group(2)

            # Short docstring
            short_doc = f'"""
 {func_name.replace("_", " ").title()}."""'

            # Insert after function definition
            lines = code.split('\n')
            lines.insert(1, short_doc)
            with_docstring = '\n'.join(lines)
            variations.append(with_docstring)

        return variations

    def augment(self, code: str, max_variations: int = 5) -> List[str]:
        """
        Create multiple augmented versions of code.

        Args:
            code: Original code
            max_variations: Maximum variations to generate

        Returns:
            List of code variations

        In C#:
        public List<string> Augment(string code, int maxVariations = 5) {
            var variations = new List<string>();
            variations.AddRange(RenameVariables(code));
            variations.AddRange(FormatVariations(code));
            variations.AddRange(AddDocstrings(code));
            return variations.Take(maxVariations).ToList();
        }
        """
        all_variations = set([code])  # Use set to avoid duplicates

        # Apply different augmentation techniques
        all_variations.update(self.rename_variables(code))
        all_variations.update(self.format_variations(code))
        all_variations.update(self.add_docstrings(code))

        # Return up to max_variations unique samples
        variations = list(all_variations)[:max_variations]

        return variations


# ============================================================================
# PART 4: Training Data Statistics
# ============================================================================

class DatasetStatistics:
    """
    Calculate statistics about code dataset.

    In C#:
    class DatasetStatistics {
        Dictionary<string, int> CalculateStats(List<string> dataset);
    }
    """

    @staticmethod
    def calculate_stats(dataset: List[str]) -> Dict:
        """
        Calculate dataset statistics.

        Returns:
            Dictionary with statistics

        In C#:
        public static Dictionary<string, object> CalculateStats(
            List<string> dataset) {
            return new Dictionary<string, object> {
                {"total_samples", dataset.Count},
                {"avg_length", dataset.Average(s => s.Length)},
                {"token_count", dataset.Sum(s => s.Split().Length)}
            };
        }
        """
        if not dataset:
            return {}

        # Basic stats
        total = len(dataset)
        lengths = [len(code) for code in dataset]
        line_counts = [len(code.split('\n')) for code in dataset]

        # Token count (rough estimate)
        token_counts = [
            len(code.replace('\n', ' ').split()) for code in dataset
        ]

        # Keyword frequency
        all_keywords = []
        for code in dataset:
            keywords = re.findall(r'\b(def|class|return|if|for|while|import)\b', code)
            all_keywords.extend(keywords)

        keyword_freq = Counter(all_keywords)

        stats = {
            'total_samples': total,
            'total_characters': sum(lengths),
            'avg_length': np.mean(lengths),
            'min_length': min(lengths),
            'max_length': max(lengths),
            'avg_lines': np.mean(line_counts),
            'total_tokens': sum(token_counts),
            'avg_tokens': np.mean(token_counts),
            'keyword_frequency': dict(keyword_freq.most_common(10))
        }

        return stats


# ============================================================================
# PART 5: Simple Code Generator (for demonstration)
# ============================================================================

class SimpleCodeGenerator:
    """
    Simple n-gram based code generator for demonstration.

    In real training, you'd use transformers, but this shows the concept.

    In C#:
    class SimpleCodeGenerator {
        Dictionary<string, List<string>> ngramModel;
        string Generate(string prompt);
    }
    """

    def __init__(self, n: int = 3):
        """
        Initialize generator with n-gram size.

        Args:
            n: Size of n-grams (default 3 = trigrams)
        """
        self.n = n
        self.ngram_model = {}  # (token1, token2, ...) -> [next_token1, next_token2, ...]

    def tokenize(self, code: str) -> List[str]:
        """
        Simple tokenization.

        In C#:
        public List<string> Tokenize(string code) {
            return code.Split(new[] {' ', '\n', '\t'});
        }
        """
        # Split on whitespace and newlines
        tokens = code.replace('\n', ' \n ').split()
        return [t for t in tokens if t]

    def train(self, code_samples: List[str]):
        """
        Train n-gram model on code samples.

        In C#:
        public void Train(List<string> codeSamples) {
            foreach (var code in codeSamples) {
                var tokens = Tokenize(code);
                UpdateNGramModel(tokens);
            }
        }
        """
        print(f"Training {self.n}-gram model on {len(code_samples)} samples...")

        for code in code_samples:
            tokens = self.tokenize(code)

            # Build n-grams
            for i in range(len(tokens) - self.n):
                # Context: n-1 tokens
                context = tuple(tokens[i:i + self.n - 1])
                # Next token
                next_token = tokens[i + self.n - 1]

                # Add to model
                if context not in self.ngram_model:
                    self.ngram_model[context] = []

                self.ngram_model[context].append(next_token)

        print(f"Learned {len(self.ngram_model)} n-gram patterns")

    def generate(self, prompt: str, max_tokens: int = 50) -> str:
        """
        Generate code from prompt.

        Args:
            prompt: Starting code
            max_tokens: Maximum tokens to generate

        Returns:
            Generated code

        In C#:
        public string Generate(string prompt, int maxTokens = 50) {
            var tokens = Tokenize(prompt).ToList();
            for (int i = 0; i < maxTokens; i++) {
                var nextToken = PredictNextToken(tokens);
                if (nextToken == null) break;
                tokens.Add(nextToken);
            }
            return string.Join(" ", tokens);
        }
        """
        tokens = self.tokenize(prompt)

        generated_tokens = 0

        while generated_tokens < max_tokens:
            # Get context (last n-1 tokens)
            if len(tokens) < self.n - 1:
                break

            context = tuple(tokens[-(self.n - 1):])

            # Predict next token
            if context in self.ngram_model:
                # Choose randomly from possible next tokens
                next_token = random.choice(self.ngram_model[context])
                tokens.append(next_token)
                generated_tokens += 1

                # Stop at function end (simple heuristic)
                if next_token == '\n' and len(tokens) > 10:
                    # Check if we're done (rough heuristic)
                    recent = ' '.join(tokens[-5:])
                    if 'return' in recent:
                        break
            else:
                # No prediction available
                break

        # Join tokens back
        code = ' '.join(tokens)

        # Clean up spacing around newlines
        code = code.replace(' \n ', '\n')

        return code


# ============================================================================
# PART 6: Complete Training Pipeline Demo
# ============================================================================

def demo_code_training_pipeline():
    """
    Demonstrate complete code training data pipeline.
    """
    print("=" * 70)
    print("CODE TRAINING DATA PIPELINE DEMO")
    print("=" * 70)
    print()

    # Sample code dataset
    raw_dataset = [
        # Good quality code
        """def add(x, y):
    return x + y""",

        """def multiply(a, b):
    result = a * b
    return result""",

        """def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n-1) + fibonacci(n-2)""",

        """def factorial(n):
    if n == 0:
        return 1
    return n * factorial(n-1)""",

        """def reverse_string(s):
    return s[::-1]""",

        # Low quality (will be filtered)
        "x=1",  # Too short

        """# Auto-generated code
def foo(): pass""",  # Auto-generated marker

        """a = 1
b = 2
c = 3
d = 4
e = 5
f = 6
g = 7
h = 8""",  # No structure

    ]

    print(f"Raw dataset size: {len(raw_dataset)} samples\n")

    # STEP 1: Data Preprocessing
    print("-" * 70)
    print("STEP 1: Data Preprocessing")
    print("-" * 70)
    print()

    preprocessor = CodeDataPreprocessor()
    cleaned_dataset = preprocessor.process_dataset(raw_dataset)

    stats = preprocessor.get_stats()
    print(f"Total samples: {stats['total']}")
    print(f"Filtered out: {stats['filtered']}")
    print(f"Cleaned samples: {stats['cleaned']}")
    print()

    # STEP 2: Data Augmentation
    print("-" * 70)
    print("STEP 2: Data Augmentation")
    print("-" * 70)
    print()

    augmenter = CodeAugmenter()
    augmented_dataset = []

    print("Augmenting code samples...")
    for code in cleaned_dataset:
        variations = augmenter.augment(code, max_variations=3)
        augmented_dataset.extend(variations)
        print(f"  {len(variations)} variations created")

    print(f"\nAugmented dataset size: {len(augmented_dataset)} samples")
    print(f"Augmentation factor: {len(augmented_dataset) / len(cleaned_dataset):.1f}x")
    print()

    # STEP 3: FIM Transformation
    print("-" * 70)
    print("STEP 3: Fill-in-the-Middle (FIM) Transformation")
    print("-" * 70)
    print()

    fim_transformer = FIMTransformer(fim_ratio=0.3)
    training_samples = fim_transformer.transform_batch(augmented_dataset)

    # Count FIM vs CLM samples
    fim_count = sum(1 for s in training_samples if s['type'] == 'FIM')
    clm_count = sum(1 for s in training_samples if s['type'] == 'CLM')

    print(f"Total training samples: {len(training_samples)}")
    print(f"  FIM samples: {fim_count} ({fim_count/len(training_samples)*100:.1f}%)")
    print(f"  CLM samples: {clm_count} ({clm_count/len(training_samples)*100:.1f}%)")
    print()

    # Show example FIM sample
    fim_example = next(s for s in training_samples if s['type'] == 'FIM')
    print("Example FIM sample:")
    print(f"  Input: {fim_example['input'][:80]}...")
    print(f"  Target: {fim_example['target'][:50]}...")
    print()

    # STEP 4: Dataset Statistics
    print("-" * 70)
    print("STEP 4: Dataset Statistics")
    print("-" * 70)
    print()

    # Calculate stats on original code (for readability)
    original_codes = [s['original'] for s in training_samples]
    dataset_stats = DatasetStatistics.calculate_stats(original_codes)

    print("Dataset Statistics:")
    print(f"  Total samples: {dataset_stats['total_samples']}")
    print(f"  Average length: {dataset_stats['avg_length']:.0f} chars")
    print(f"  Average lines: {dataset_stats['avg_lines']:.1f}")
    print(f"  Total tokens: {dataset_stats['total_tokens']}")
    print(f"  Average tokens: {dataset_stats['avg_tokens']:.0f}")
    print()
    print("Top keywords:")
    for keyword, count in dataset_stats['keyword_frequency'].items():
        print(f"  {keyword}: {count}")
    print()

    # STEP 5: Simple Code Generation
    print("-" * 70)
    print("STEP 5: Simple Code Generation Demo")
    print("-" * 70)
    print()

    # Train simple n-gram model
    generator = SimpleCodeGenerator(n=3)
    generator.train(cleaned_dataset)

    # Generate code
    prompts = [
        "def add",
        "def factorial",
        "def reverse"
    ]

    print("Generating code from prompts:\n")
    for prompt in prompts:
        generated = generator.generate(prompt, max_tokens=20)
        print(f"Prompt: {prompt}")
        print(f"Generated: {generated}")
        print()

    # Summary
    print("=" * 70)
    print("PIPELINE SUMMARY")
    print("=" * 70)
    print()
    print("✅ Cleaned and filtered raw code data")
    print("✅ Augmented data with variations")
    print("✅ Applied Fill-in-the-Middle transformation")
    print("✅ Generated training samples (FIM + CLM)")
    print("✅ Calculated dataset statistics")
    print("✅ Demonstrated simple code generation")
    print()
    print("Training pipeline complete!")
    print()


# ============================================================================
# MAIN EXECUTION
# ============================================================================

if __name__ == "__main__":
    """
    Run the code training pipeline demo.

    In C#:
    static void Main(string[] args) {
        DemoCodeTrainingPipeline();
    }
    """
    demo_code_training_pipeline()

    print()
    print("=" * 70)
    print("NEXT STEPS")
    print("=" * 70)
    print()
    print("1. Try the pipeline with your own code samples")
    print("2. Experiment with different FIM ratios (0.3 = 30%)")
    print("3. Add more augmentation techniques")
    print("4. Try different n-gram sizes (n=2, n=4, n=5)")
    print("5. Collect code from GitHub for larger dataset")
    print()
    print("In real training:")
    print("  • Use transformer models instead of n-grams")
    print("  • Train on millions of code samples")
    print("  • Use GPUs for faster training")
    print("  • Fine-tune on specific programming languages")
    print()
    print("In Lesson 9, we'll build actual code generation & completion!")
    print("=" * 70)
